### ISSUE TITLE
Create a burner wallet implementation that works with wagmi and rainbow

### ISSUE THREAD

**Issue by ShravanSunder** [scaffold-eth/se-2#1]
## Overview
- [x] create a burner wallet connector for wagmi
- [x] add burner connector to rainbow wallet
- todo: #9

## Details
Based on config values
- should log into burner wallet in the background on startup for localhost
- should disable burner wallet for other networks
- config to disable burner wallet entirely
- config to disable auto login to burner on localhost

**Comment by carletex** [comment]
@ShravanSunder  Still not sure about how the `scaffold.config.json` would work. But some thoughts:

- How this co-exist or how is it different from a .env file?
- I think it should be `js` not `json`. So we can have some JS logic (like getting env vars there)
- I think it should live in the root
- It should be there and work out of the box, no need to generate it and no need to configure anything if you don't want to.

**Comment by ShravanSunder** [comment]
@carletex  some thoughts
1. we can assume defaults and use that without generating it.  I"m also good with ts file.  
2. env variables are different than config.  env variables are keys that are based on environment.  So you can have API keys that are not checked in and based on prod, staging, dev env.  They allow layering.  This will be good for api keys
3. I think we can load env variables in the config.  
4. config should be fore things like the burner wallet settings.  they are not env variable based and impact runtime.

**Comment by ShravanSunder** [comment]
@carletex here's a video overview, its ready for PR:  https://www.dropbox.com/s/f4trel929a2jeou/2022.09.30-21.07-Brave%20Browser%20Scaffod-eth%20App.mp4?dl=0

I'll do the config as a seperate PR i think.  better to split things up.  

this is the burner config so far
```
export type TAutoConnect = {
  /**
   * Enable the burner wallet.  If this is disabled, burner wallet is entierly disabled
   */
  enableBurnerWallet: boolean;
  /**
   * Always autoConnectToBurner to burner wallet on page load.
   */
  alwaysAutoConnectToBurnerOnLoad: boolean;
  /**
   * If user is not connected to any wallet:  On reload, connect to burner wallet
   */
  connectToBurnerIfDisconnectedOnLoad: boolean;
  /**
   * Auto connect: If the user was connected into a wallet before, on page reload reconnect automatically
   */
  allowAutoConnect: boolean;
};
```

**Comment by ShravanSunder** [comment]
was thinking to simplify the options.  @carletex 
```ts
export type TAutoConnect = {
  /**
   * Enable the burner wallet.  If this is disabled, burner wallet is entierly disabled
   */
  enableBurnerWallet: boolean;
  /**
   * Auto connect:
   * 1. off
   * 2. autoConnectIfNotDisconnected: If the user was connected into a wallet before, on page reload reconnect automatically
   * 3. alwaysConnectToBurner: Always autoConnectToBurner to burner wallet on page load.
   * 4. autoConnectToBurnerIfDisconnectedOnLoad: If user is not connected to any wallet:  On reload, connect to burner wallet
   */
  allowAutoConnect:
    | "off"
    | "autoConnectIfNotDisconnected"
    | "alwaysAutoConnectToBurner"
    | "autoConnectToBurnerIfDisconnected";
};

```

**Comment by ShravanSunder** [comment]
The options have been changed @carletex 
```
export type TAutoConnect = {
  /**
   * Enable the burner wallet.  If this is disabled, burner wallet is entierly disabled
   */
  enableBurnerWallet: boolean;
  /**
   * Auto connect:
   * 1. If the user was connected into a wallet before, on page reload reconnect automatically
   * 2. If user is not connected to any wallet:  On reload, connect to burner wallet
   */
  autoConnect: boolean;
};
```
