### ISSUE TITLE
Rainbowkit modal does not close after connecting wallet

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/se-2#110]
### Description 
There is some issue with rainbokit wallet, Once you connect your wallet the modal that states the connected wallet address does not close(you need to refresh the page to close it) : 

https://user-images.githubusercontent.com/80153681/214639220-c4ecad08-3d7b-48fa-9f38-00a064996efd.mov

This is the known issue with rainbowkit and is posted here -> https://github.com/rainbow-me/rainbowkit/issues/837

**Comment by carletex** [comment]
It seems that this will fix it: https://github.com/wagmi-dev/wagmi/pull/1679

BTW, If you resize the screen... the modal closes :D (at least on my case)

**Comment by technophile-04** [comment]
> BTW, If you resize the screen... the modal closes :D (at least on my case)
Yup, working for me too :)

**Comment by KcPele** [comment]
I just tried using rainbow-ui-kit. and I noticed the model doesn't close just like the one here. so it's from the library

**Comment by carletex** [comment]
https://github.com/wagmi-dev/wagmi/pull/1679 This was merged on the wagmi side!

Now we need to wait until Rainbow kit update their wagmi peer dep: https://github.com/rainbow-me/rainbowkit/pull/1000

**Comment by carletex** [comment]
Both wagmi & rainbow kit PRs were merged!

Let's update the packages and hope that it fixes this annoying error :D

cc @technophile-04 @rin-st @sverps

**Comment by technophile-04** [comment]
@rin-st really sorry, actually I was working on this and forgot to assign myself :(

**Comment by rin-st** [comment]
no problem :)
