### ISSUE TITLE
Upgrade to Next13

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#120]
I think upgrading to Next13 shouldn't be too complicate, since we are not using most of the features.

https://nextjs.org/docs/upgrading

This is not urgent, but we can give it a go and see if all goes smooth.

I personally would avoid using the beta features for now, like:
![image](https://user-images.githubusercontent.com/2486142/215711770-6ccc51d5-7d5b-4784-80e4-a3aae71659d7.png)

Thoughts? @technophile-04 @rin-st

**Comment by rin-st** [comment]
Yup, I think it will be no problems with the upgrade. We don't need that beta features since we have to make base functionality first and experiment later. We can always add them later if we need to. I hope it will not break things like surge (not sure what we need to do first).

**Comment by carletex** [comment]
I'd say: let's tackle this first and the surge... in case the build process in Next13 is different.

Maybe we need to tweak <Image>, <Link> components (as they say in the upgrade guide.).
