### ISSUE TITLE
Update fixed elements on mobile

### ISSUE THREAD

**Issue by rin-st** [scaffold-eth/se-2#123]
Right now, fixed elements look strange, and we need to think about what to do with them.

https://user-images.githubusercontent.com/25638585/216045432-2abacc06-8a05-4d42-b9eb-77bc9f20a795.mov

Simplest solutions:
1. Add background to theme-switcher
2. Move elements to the footer and make them non-fixed.

**Comment by sverps** [comment]
I think adding a background is the better option. It keeps those buttons easily accessible and doesn't give up a lot of screen real estate (since the buttons were already making this area not really useful for the things behind it).
