### ISSUE TITLE
Improve new useScaffoldContract* hooks

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/se-2#125]
The main aim of this issue is to keep track of all the improvements/bugs mentioned/noticed as we move towards `beta-launch` and improve it. Some of these TODOs will also be handled by #116 

- [ ] #116 
- [x] #127

**Comment by carletex** [comment]
@technophile-04 I think we can just create single issues whenever we find something to fix regarding hooks. Thanks for this!
