### ISSUE TITLE
Hiding toast from "react-hot-toast"

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#138]
![image](https://user-images.githubusercontent.com/2486142/217768837-802511ad-93b1-421c-a00d-b2b4781f87e2.png)

This is a minor/non-important issue, but improves DX.

 It would be nice to be able to "hide" for the builder `toast` from ""react-hot-toast". It's a bit confusing. Not sure if there is a way to hide that dependecy.

Or maybe we can just rename our "toast" to something else: "alert", "notification"?

**Comment by rin-st** [comment]
Yep, changing the name of our component to `notification` is better for DX. I hope that will be enough for most cases

**Comment by technophile-04** [comment]
> Yep, changing the name of our component to notification is better for DX. I hope that component will be enough for most cases

💯💯 `notification` seems good, just to plug in maybe `scaffoldNotification` 🤔 but even `notification` is great 🙌

**Comment by carletex** [comment]
`notification` it is!! This issue is up for grabs now.

Thanks :)
