### ISSUE TITLE
useScaffoldEventsRead hook

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#142]
A way to read past events from a given contract, and listening to new events.

We can see what wagmi offers, and create a hook on top of it (as in useScaffoldContractRead & useScaffoldContractWrite)

**Comment by KcPele** [comment]
It should keep track of past event and listens for new event that will be added to the past event. 
- should it listen for any event from the smart contract or accept the event name and keep track of that particular one?

**Comment by KcPele** [comment]
#162
