### ISSUE TITLE
Better Wrong network display + switch

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#165]
This is the current wrong network display that we have (our metamask is on mainnet, but the targetNetwork is hardhat):

![image](https://user-images.githubusercontent.com/2486142/219076728-72a0a7bc-4005-4c69-a2b7-d26ec47301b9.png)

Yesterday, we were connecting with an external wallet (punk wallet) through wallet connect and we were on the wrong network. For some reason the "switch" button didn't work and we were locked (no way to change the wallet, change network, or disconnect).

Let's do something similar as the default `<ConnectButton>` from RainbowKit does when the network is unsupported. 

1. Shows an error button:
![image](https://user-images.githubusercontent.com/2486142/219078104-1e313ec2-a75d-4d4a-bd65-a3bbe77d9c71.png)

2. When clicking it show this modal, that allows you to disconnect or switch. 
![image](https://user-images.githubusercontent.com/2486142/219078207-ebe764cf-8a3f-457e-8d46-8fe7e45aa12e.png)

If this is something that we can do in `RainbowKitCustomConnectButton` with the built-in props (like `openAccountModal, openChainModal, openConnectModal`), lets go for it.

If not, lets have that "Wrong network" button to have a dropdown with 2 options
1. Switch to mainnet (or whatever target networt)
2. Disconnect wallet.

**Comment by carletex** [comment]
BTW, if you want to test the `<ConnectButton>` from RainbowKit, you can:

1. Use `ConnectButton`  in the `Header.tsx` component, instead of `RainbowKitCustomConnectButton`
2. Connect your metamask
3. Switch it to a network that it's not in `wagmiConnectors` (or remove a chain from the file and connect to it)
![image](https://user-images.githubusercontent.com/2486142/219080596-f34a5aa7-b514-4f5d-bbff-756d6f6dde8a.png)

**Comment by KcPele** [comment]
working on that. the second one is much better

**Comment by KcPele** [comment]
I just made use of the openChainModal and customized the wrong network button.
To do something exactly https://github.com/scaffold-eth/se-2/issues/165#issue-1586095484. there will be some logic and thereby increasing the amount of code in the custom button large
#175
https://github.com/scaffold-eth/se-2/pull/175/commits/6296e366e4b86aff4210facd20ac40d752eb8d43

**Comment by KcPele** [comment]
Here is another update #204 I just made some little changes.

**Comment by carletex** [comment]
Fixed on #204
