### ISSUE TITLE
Mobile design: spacing / padding / margin

### ISSUE THREAD

**Issue by sverps** [scaffold-eth/se-2#183]
I believe there is often too much whitespace on mobile that takes up valuable screen real estate.

![Screenshot_20230217_220430](https://user-images.githubusercontent.com/15879327/219797468-a4f17a2a-4ec8-4e21-9262-a68e4fe5ab3b.png)

I propose a couple of small tweaks to make better use of small screens.

![Screenshot_20230217_221452](https://user-images.githubusercontent.com/15879327/219797591-b3b67aec-9d30-4547-a56a-b786e77d5f10.png)

**Comment by carletex** [comment]
Looks good!
