### ISSUE TITLE
Multiple deployed contracts UI

### ISSUE THREAD

**Issue by sverps** [scaffold-eth/se-2#186]
I didn't find any discussion about handling multiple contracts. I think it could be nice to add some UI for it (that would only render when there actually are multiple contracts).

Should this be explored further and build something like this:
![image](https://user-images.githubusercontent.com/15879327/219871089-24ab1257-3b8f-4397-86ab-689721731f6d.png)

Or is it 'good enough' to let a developer figure it out on his own, and just add additional ContractUI components underneath like so:
```
<div className="flex justify-center">
  <div className="grid grid-cols-1 lg:grid-cols-6 py-12 px-10 lg:gap-12 w-full max-w-7xl my-0">
    <ContractUI contractName="YourContract" />
    <ContractUI contractName="OtherContract" />
  </div>
</div>
```

Which looks like this:
![image](https://user-images.githubusercontent.com/15879327/219871827-984a4b23-85eb-49a3-8542-9a8977397a3e.png)

**Comment by carletex** [comment]
> Or is it 'good enough' to let a developer figure it out on his own, and just add additional ContractUI components underneath like so

This is how it's done in SE1.

But I guess we could easily parse the `hardhat_contract` file, and display the deployed contracts on the selected network in the Debug Contract page.

Thoughts? 

Not a priority tho!

**Comment by sverps** [comment]
I'm leaning towards adding this. I believe scaffold-eth should cater to all types of learners, so also to people that focus on solidity and just want a nice contract debugging interface, but don't necessarily want to learn how to mess with react.

The interface for desktop is simple and clear enough I believe. I'll try and iterate a bit on a suitable mobile design.

**Comment by rin-st** [comment]
I think you can create something like `const CONTRACTS_TO_SHOW = ["YourContract", "YourContractTwo", "YourContractThree"];` at the top of your `/debug` page and map through it. And also create a header like `Contract: YourContract` for every contract, and some divider between contracts.

**Comment by rin-st** [comment]
oh, I didn't see tabs for contracts. Probably it will be even better

**Comment by carletex** [comment]
> I think you can create something like const CONTRACTS_TO_SHOW = ["YourContract", "YourContractTwo", "YourContractThree"];

I'd lean into getting the deployed contracts dynamically from `hardhat_contracts.json` (from the current target network). The tabs looks cool!

**Comment by sverps** [comment]
On mobile, I kept mostly the same "pills", but instead of wrapping, they're horizontally scrollable:

![image](https://user-images.githubusercontent.com/15879327/220940172-665d2260-32bd-4ffc-b9f9-c2e9c019776a.png)
