### ISSUE TITLE
Make { data } for useScaffoldContractRead to be "any"

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#189]
Until we get the autocompletion / type inference right. For now we'll avoid:

![b](https://user-images.githubusercontent.com/2486142/220173692-ee58054d-c8f0-4e5a-851a-7f8ce25a9303.png)
![a](https://user-images.githubusercontent.com/2486142/220173701-3fa78ac4-e9c3-4f35-877d-398c474b1b33.png)

Check https://github.com/scaffold-eth/se-2/pull/147#issuecomment-1437373694

**Comment by sverps** [comment]
I'll take this.

I think it would also be good to allow a generic type that defaults to `any`, then at least whoever wants some better types can set them manually.
