### ISSUE TITLE
Faucet Component

### ISSUE THREAD

**Issue by edakturk14** [scaffold-eth/se-2#19]
# Faucet Component

Create a Faucet Component that will give funds to the user when they are connected to the Burner Wallet. 

## Detailed Explanation

Create a new button that will only be displayed when the user is connected to the burner wallet. When a user clicks on the button it will send funds to the users burner wallet. 

The button will send 1 ETH, so it will not ask the user for an input for simplicity. In the future we can have the functionality for the user to choose the amount. For the initial feature lets make the button send 1 ETH by default. 

Here is a sample image for reference: (We can edit the name or have an icon for the faucet button)
<img width="641" alt="Screen Shot 2022-10-14 at 11 38 25" src="https://user-images.githubusercontent.com/22100698/195897992-38509c74-4edb-4785-9f91-002854c62eae.png">

## Links

As a reference we can use the [Faucet Component in Scaffold-eth](https://github.com/scaffold-eth/scaffold-eth/blob/5bdaf150c8007ba41abdd8c5763203a18baaa873/packages/react-app/src/components/Faucet.jsx)

**Comment by technophile-04** [comment]
Thanks 🙌, will work on this
