### ISSUE TITLE
Contract UI component

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#2]
UI that adapts to the contract ABI (stored in packages/frontend/contracts/hardhat_contracts.json when you deploy)

It depends on a bunch of components and hooks. We'd figure out what we need as we go, creating issues as needed.

- [x] Address https://github.com/scaffold-eth/se-2/commit/8b327f4d647ca562ae104a699443b49bc2f0ebd0
- [x] AddressInput https://github.com/scaffold-eth/se-2/issues/3
- [x] Balance https://github.com/scaffold-eth/se-2/issues/4
- [ ] Transactor helper?

I'd do a hard refactor on the Contract component (to make it cleaner and easier to mantain). But as a reference we can use:
- scaffold-eth [Contract component](https://github.com/scaffold-eth/scaffold-eth/tree/master/packages/react-app/src/components/Contract)
- abi ninja [Contract component](https://github.com/carletex/abi.ninja/tree/master/packages/react-app/src/components/Contract). It has a better UX
- Naim's [debug-eth-contract](https://github.com/Naim-Bijapure/debug-eth-contract)

**Comment by ShravanSunder** [comment]
@carletex We'l be using tailwind / headless ui and daisy for this component?

**Comment by carletex** [comment]
MVP done on #36
