### ISSUE TITLE
Improve input form conversions

### ISSUE THREAD

**Issue by sverps** [scaffold-eth/se-2#203]
The following issues were encountered:
- Converting uint to ether throws an error when the form is empty.
- Converting uint to ether throws error when pressing the asterix multiple times
- Conversion button hitboxes are too small (see also #170 )

![image](https://user-images.githubusercontent.com/15879327/220878857-eb17a6d4-1b86-407e-a53f-62fb77fdfdcd.png)

**Comment by KcPele** [comment]
Are you working on it? I can jump on it if you don't mind

**Comment by KcPele** [comment]
> The following issues were encountered:
> 
> * Converting uint to ether throws an error when the form is empty.
> * Converting uint to ether throws error when pressing the asterix multiple times
> * Conversion button hitboxes are too small (see also [fix(multiply string): make the button hitbox larger to improve UX #170](https://github.com/scaffold-eth/se-2/pull/170) )
> 
> ![image](https://user-images.githubusercontent.com/15879327/220878857-eb17a6d4-1b86-407e-a53f-62fb77fdfdcd.png)

How so i reproduce the error

**Comment by sverps** [comment]
I'm working on it, but I have another issue that you can take. Creating it in a sec

**Comment by KcPele** [comment]
> I'm working on it, but I have another issue that you can take. Creating it in a sec

ok great
