### ISSUE TITLE
Contract data display overflows for bytes32 

### ISSUE THREAD

**Issue by sverps** [scaffold-eth/se-2#205]
Modify one of the contract public fields to be bytes32 and you'll see the following issue:

![image](https://user-images.githubusercontent.com/15879327/220884329-9d2719f9-6cf3-4926-87ea-4bc0196da438.png)

@KcPele

**Comment by KcPele** [comment]
Great

**Comment by carletex** [comment]
maybe just a `word-break: break-all;` ?

**Comment by KcPele** [comment]
on that

**Comment by KcPele** [comment]
@sverps can u explain in detail how i can reproduce the issue

**Comment by KcPele** [comment]
fixed. #207
