### ISSUE TITLE
Better UX/UI on contract methods (/debug page)

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#218]
**We want to go from:**
![old](https://user-images.githubusercontent.com/2486142/221902035-e5aec2f7-3fb9-4b89-b40d-6c3b8faf07fc.png)

**To something like:**
![new](https://user-images.githubusercontent.com/2486142/221901965-c2888fa8-4c5a-4618-b478-54f5a4321890.png)

Changes:
- Remove dropdown functionality (besides removing the caret, remove the un-needed classes)
- Separator between methods (use base-300 color)
- When there is no argument, align the button with the method name.
- The asterisk * is too big, let's use the smaller unit
- Top / bottom spacing (between methods and also between the methods and the wrapper)

**Comment by carletex** [comment]
This is up for grabs! (The screenshot is just me hacking it with dev tools in Chrome :D)

cc @rin-st @technophile-04

**Comment by technophile-04** [comment]
Love it !!!
