### ISSUE TITLE
Migrate from env's to config fiile

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/se-2#230]
I think we should use `*.config.ts`  file in our frontend for `targeetNetwork`, `pollingInterval` etc instead of relying on `env's`. 

### Reasons / Advantages : 
1. The main reason for putting this discussion is #202, using a `.ts` will help us infer literal types of `targetNetwork` which would be a great help for issue 202, as currently I can the showstopper for issue 202 is figuring out proper `targetNetwork` at compile time itself which will lead to type autocompletion as mentioned in this comment -> https://github.com/scaffold-eth/se-2/pull/202#issuecomment-1441963792
2. We will be able to force people to use `supported` wagmi networks only and it will also eleminate the chances of spelling mistakes and people refering / finding chains on wagmi docs. checkout out : 

https://user-images.githubusercontent.com/80153681/224123396-cefcf9de-d763-4c93-bee8-60e440562c4a.mov

 3. Also our single source of truth will be hand in hand with `wagmi` referring to -> #188 
 4. Currently if people use chains like `polygonMumbai` / others and make transactions, you don't get a link to their block explorer, since we are currently handling only `etherscan` checkout -> https://github.com/scaffold-eth/se-2/blob/5fb5e5f90e655d6d2b0df04dafe19c85a13f5632/packages/nextjs/utils/scaffold-eth/networks.ts#L70
 
You don't get any link to `blockexplorer` if you make transaction on Mumbai testnet or similar : 
![Screenshot 2023-03-10 at 12 22 07 AM](https://user-images.githubusercontent.com/80153681/224126073-bf457b64-b196-40ac-b288-d4cbeffb3c31.jpg)

while using wagmi's chain we can already leverage it(we can handle this in the current main branch too though). 

---

I think the reason we were not using `*config.ts` and were using `env's` initially was that it made more sense at that time since we were not that much relying on env's and them being typed also its easy to leverage env's in Next. 

some discussion on this topic was also found here -> https://github.com/scaffold-eth/se-2/issues/1#issuecomment-1259236623

--- 

Would love to hear the thoughts of other on this 🙌, specifically  : 
1. Do we really need `*.config.ts`, will it be helpful that much and improve DX ? 
2. If at all we plan to create `*.config.ts` should make it global like one `*.config.ts` file for both `hardhat` and `nextjs` ? 
3. ....

cc @carletex @rin-st @sverps

**Comment by carletex** [comment]
Hey @technophile-04 ! Thanks for creating the issue and drafting a PR as we discussed on DMs.

Love the advantages! <3

> Do we really need *.config.ts, will it be helpful that much and improve DX ?

I think it improve it quite a lot, so it makes sense to at least try and see how it feels :)

> If at all we plan to create *.config.ts should make it global like one *.config.ts file for both hardhat and nextjs ?

Having a SE-2 config source of truth would be ideal. We could use the targetNetwork also for hardhat.... even having the list of networks metadata (color / RPC / etc) in the config file (as in `packages/nextjs/utils/scaffold-eth/networks.ts`) to have a single network config. Yesterday we wanted to deploy to the gnosis chain, and we had to:

1. Change `targetNetwork` on .env.dev & .env.prod
2. (optional) Add the gnosis color to NETWORKS_EXTRA_DATA 
3. Modify the `hardhat.config.ts` to add the gnosis chain and its RPC.

Having 1 single file will improve the experience for sure, specially for Networks, which is the main element on a dapp.

Not sure if we'd have issues with the monorepo or not. If it's straight forward, I'd go for it... but we can also do a few iterations and starting with NextJS only.

**Misc**:
- Do we need a dev config inside the config.ts file? .env.development / .env.production allow us to have different setting depending on the env. Maybe is not worth it, just thinking out loud.
- Secrets (to use on nextjs backend) will still need to be env vars. (.env.local for local dev / Vercel env vars for production APP)
