### ISSUE TITLE
wagmi isLoading & isSuccess. Add isMining in our custom hooks?

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#236]
When sending a tx, wagmi flags work like this:

**isLoading**: tx being sent to the mempool
**isSuccess**: tx succesfully sent to the mempool

I'd like to have a flag "isMining" that is true until the TX is mined. I think we could add it into our `useScaffoldContractWrite.ts`. Unless I'm missing something :upside_down_face: 

I created this branch with everything set up to test:
https://github.com/scaffold-eth/se-2/tree/test-isLoading

YourContract Goerli address contract: 0x194391b38342E2B776f0ada0b3F0f024b2221e19

hardhat_contracts.json

```json
{
  "5": [
    {
      "name": "goerli",
      "chainId": "5",
      "contracts": {
        "YourContract": {
          "address": "0x194391b38342E2B776f0ada0b3F0f024b2221e19",
          "abi": [
            {
              "inputs": [
                {
                  "internalType": "address",
                  "name": "_owner",
                  "type": "address"
                }
              ],
              "stateMutability": "nonpayable",
              "type": "constructor"
            },
            {
              "anonymous": false,
              "inputs": [
                {
                  "indexed": false,
                  "internalType": "address",
                  "name": "greetingSetter",
                  "type": "address"
                },
                {
                  "indexed": false,
                  "internalType": "string",
                  "name": "newGreeting",
                  "type": "string"
                },
                {
                  "indexed": false,
                  "internalType": "bool",
                  "name": "premium",
                  "type": "bool"
                },
                {
                  "indexed": false,
                  "internalType": "uint256",
                  "name": "value",
                  "type": "uint256"
                }
              ],
              "name": "GreetingChange",
              "type": "event"
            },
            {
              "inputs": [],
              "name": "greeting",
              "outputs": [
                {
                  "internalType": "string",
                  "name": "",
                  "type": "string"
                }
              ],
              "stateMutability": "view",
              "type": "function"
            },
            {
              "inputs": [],
              "name": "owner",
              "outputs": [
                {
                  "internalType": "address",
                  "name": "",
                  "type": "address"
                }
              ],
              "stateMutability": "view",
              "type": "function"
            },
            {
              "inputs": [],
              "name": "premium",
              "outputs": [
                {
                  "internalType": "bool",
                  "name": "",
                  "type": "bool"
                }
              ],
              "stateMutability": "view",
              "type": "function"
            },
            {
              "inputs": [
                {
                  "internalType": "string",
                  "name": "_newGreeting",
                  "type": "string"
                }
              ],
              "name": "setGreeting",
              "outputs": [],
              "stateMutability": "payable",
              "type": "function"
            },
            {
              "inputs": [],
              "name": "totalCounter",
              "outputs": [
                {
                  "internalType": "uint256",
                  "name": "",
                  "type": "uint256"
                }
              ],
              "stateMutability": "view",
              "type": "function"
            },
            {
              "inputs": [
                {
                  "internalType": "address",
                  "name": "",
                  "type": "address"
                }
              ],
              "name": "userGreetingCounter",
              "outputs": [
                {
                  "internalType": "uint256",
                  "name": "",
                  "type": "uint256"
                }
              ],
              "stateMutability": "view",
              "type": "function"
            },
            {
              "inputs": [],
              "name": "withdraw",
              "outputs": [],
              "stateMutability": "nonpayable",
              "type": "function"
            },
            {
              "stateMutability": "payable",
              "type": "receive"
            }
          ]
        }
      }
    }
  ]
}
```

**Comment by rin-st** [comment]
First 10 secs and last 10 secs

https://user-images.githubusercontent.com/25638585/225395927-869e05ec-7be5-4fb1-a3ad-78a3f217404f.mov

**Comment by carletex** [comment]
> Please check if it works as expected @carletex

Yes, it does!

> Should it be true before sending a transaction (when isLoading is true)?

Yep, I think so. I like how it's now. Even if technically is not mining yet :D


Wan't to create a PR? Remove my dev comments, revert to hardhat on .env.dev etc

Thanks!!

**Comment by technophile-04** [comment]
If at all we want to be more specific we can use [`useWaitForTransaction`](https://wagmi.sh/react/hooks/useWaitForTransaction)

```ts
const {isSucess} = useWaitForTransaction({
    hash: wagmiContractWrite.data?.hash,
  })
```

`isSuccess ` guarantees that 1 block is mined we can also use `isLoading` which in our case `isMining` maybe

**Comment by rin-st** [comment]
Good point, thanks! But in this case, we will need to change the logic, and handle `if`'s of our hook etc to add this. Also, we will need to add an additional variable to combine `useContractWrite`'s `isLoading` and `useWaitForTransaction` `isLoading`. So adding one simple `isMining` seems easier and better
https://github.com/scaffold-eth/se-2/pull/244

**Comment by KcPele** [comment]
> If at all we want to be more specific we can use [`useWaitForTransaction`](https://wagmi.sh/react/hooks/useWaitForTransaction)
> 
> ```ts
> const {isSucess} = useWaitForTransaction({
>     hash: wagmiContractWrite.data?.hash,
>   })
> ```
> 
> `isSuccess ` guarantees that 1 block is mined we can also use `isLoading` which in our case `isMining` maybe

I really think these will be better
const {isSucess: isMinning} = useWaitForTransaction({ hash: wagmiContractWrite.data?.hash,
  })

then we can simply return isMinning

**Comment by KcPele** [comment]
am currently giving it a try :100:

**Comment by sverps** [comment]
> const {isSucess: isMinning} = useWaitForTransaction({ hash: wagmiContractWrite.data?.hash,
> })

Maybe something like this:

```typescript
export const useScaffoldContractWrite = (contractName: string, functionName: string, args?: any[], value?: string) => {
  const configuredChain = getTargetNetwork();
  const { data: deployedContractData } = useDeployedContractInfo(contractName);
  const { chain } = useNetwork();
  const writeTx = useTransactor();
  const [isMining, setIsMining] = useState(false);

  const wagmiContractWrite = useContractWrite({
    mode: "recklesslyUnprepared",
    chainId: configuredChain.id,
    address: deployedContractData?.address,
    abi: deployedContractData?.abi,
    args,
    functionName,
    overrides: {
      value: value ? utils.parseEther(value) : undefined,
    },
  });

  const { isSuccess } = useWaitForTransaction({
    hash: wagmiContractWrite.data?.hash,
  });
  useEffect(() => {
    if (isSuccess) {
      setIsMining(false);
    }
  }, [isSuccess]);

  const sendContractWriteTx = async () => {
    if (!deployedContractData) {
      notification.error("Target Contract is not deployed, did you forgot to run `yarn deploy`?");
      return;
    }
    if (!chain?.id) {
      notification.error("Please connect your wallet");
      return;
    }
    if (chain?.id !== configuredChain.id) {
      notification.error("You on the wrong network");
      return;
    }

    if (wagmiContractWrite.writeAsync) {
      try {
        setIsMining(true);
        await writeTx(wagmiContractWrite.writeAsync());
      } catch (e: any) {
        const message = getParsedEthersError(e);
        notification.error(message);
      }
    } else {
      notification.error("Contract writer error. Try again.");
      return;
    }
  };

  return {
    ...wagmiContractWrite,
    isMining,
    // Overwrite wagmi's write async
    writeAsync: sendContractWriteTx,
  };
};
```

**Comment by sverps** [comment]
I like the `useWaitForTransaction` approach.

Maybe something like this (since we also want to clear the `isMining` flag when there's an error, etc:

``typescript
export const useScaffoldContractWrite = (contractName: string, functionName: string, args?: any[], value?: string) => {
  const configuredChain = getTargetNetwork();
  const { data: deployedContractData } = useDeployedContractInfo(contractName);
  const { chain } = useNetwork();
  const writeTx = useTransactor();
  const [isMining, setIsMining] = useState(false);

  const wagmiContractWrite = useContractWrite({
    mode: "recklesslyUnprepared",
    chainId: configuredChain.id,
    address: deployedContractData?.address,
    abi: deployedContractData?.abi,
    args,
    functionName,
    overrides: {
      value: value ? utils.parseEther(value) : undefined,
    },
  });

  const { isLoading: isWaitingForTransaction } = useWaitForTransaction({
    hash: wagmiContractWrite.data?.hash,
  });
  useEffect(() => {
    if (!isWaitingForTransaction) {
      setIsMining(false);
    }
  }, [isWaitingForTransaction]);

  const sendContractWriteTx = async () => {
    if (!deployedContractData) {
      notification.error("Target Contract is not deployed, did you forgot to run `yarn deploy`?");
      return;
    }
    if (!chain?.id) {
      notification.error("Please connect your wallet");
      return;
    }
    if (chain?.id !== configuredChain.id) {
      notification.error("You on the wrong network");
      return;
    }

    if (wagmiContractWrite.writeAsync) {
      try {
        setIsMining(true);
        await writeTx(wagmiContractWrite.writeAsync());
      } catch (e: any) {
        const message = getParsedEthersError(e);
        notification.error(message);
      }
    } else {
      notification.error("Contract writer error. Try again.");
      return;
    }
  };
  console.log({ isMining, isWaitingForTransaction });
  return {
    ...wagmiContractWrite,
    isMining,
    // Overwrite wagmi's write async
    writeAsync: sendContractWriteTx,
  };
};
```

**Comment by rin-st** [comment]
```
const { isLoading: isWaitingForTransaction } = useWaitForTransaction({
    hash: wagmiContractWrite.data?.hash,
  });

...
return {
    ...wagmiContractWrite,
    isMining: isLoading || isWaitingForTransaction,
    // Overwrite wagmi's write async
    writeAsync: sendContractWriteTx,
  };
```
is enough, but it duplicates work from transactor, so it seems not needed

**Comment by carletex** [comment]
I agree with @rin-st here. The approach he took on https://github.com/scaffold-eth/se-2/pull/244 seems to be working fine and it's simple.

The `transactor` is already waiting for the TX to mine.

> since we also want to clear the isMining flag when there's an error

Yep, but I think we are already doing that (resetting on the `finally` block), right?
