### ISSUE TITLE
Vercel builds fails

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#254]
I connected this https://github.com/BuidlGuidl/hackathon-se2 to Vercel in the Vercel UI, so it deploys when I push to `main`.

It fails when I try to deploy (The initial deploy from the cli worked). It gets these errors:

![image](https://user-images.githubusercontent.com/2486142/227333638-0f57420b-2161-416a-b527-776918e70144.png)

I guess this is happening since #202 and we talked about this before.

- I just added the generated `hardhat_contract.ts` file to the repo (even tho my project won't use any contract). Not the best solution because:
 
    1. Doesn't make sense when your project doesn't use any contract (a lot of times you build dapps that don't use a custom contract)
    2. If you use a contract, the file will change all the time when you are developing locally (the address of the local contract will change on each deployment).

What solutions do we have?

**Comment by sverps** [comment]
Found a solution by using some more Typescript magic. :sweat_smile:

**Comment by abasedape** [comment]
ahhh so what is the solution ?lol

**Comment by sverps** [comment]
> ahhh so what is the solution ?lol

I opened a PR for it (see the linked pull request just above my comment) #255

**Comment by carletex** [comment]
Love your TS magic @sverps <3
