### ISSUE TITLE
Postinstall fail on windows

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/se-2#275]
Its seems that there is some problem when resolving the path while creating the generated file. 

Sharing below a SS from the TG group facing an issue : 
![IMG_2385](https://user-images.githubusercontent.com/80153681/228966232-117f9cf2-13f8-42b6-b7fa-089875c1420a.JPG)

Its seems its resolving c:\\c:\\ instead of c:\\

**Comment by carletex** [comment]
We should have a proper way to test this. VM on linux/macOS? XD

@ZakGriffith are you still on windows? If so, could you try?

----

Also, maybe we should just un-gitignore this file? @sverps mentioned at some point. 

- If you connect your GH repo to vercel, and want to interact with a live contract with your dapp....you need to un-gitignore and commit the file

Thoughts?

**Comment by sverps** [comment]
Yeah maybe that's better. We'll need to worry a lot less about build pipelines and the postinstall script etc.

When we make changes to the contract for testing stuff, we need to be mindful of not committing that one anayway, might as well keep an eye out for changes to `hardhat_contracts` file from being committed by accident.

**Comment by carletex** [comment]
Ok, let's go with it and see how it feels.

https://github.com/scaffold-eth/se-2/issues/278

**Comment by 0xPro** [comment]
i'm on windows and just needed to change this. not sure if it'll affect mac users though
`const __dirname = path.dirname(new URL(import.meta.url).pathname).slice(1);`

**Comment by carletex** [comment]
This issue will be fixed with https://github.com/scaffold-eth/se-2/issues/278

**Comment by technophile-04** [comment]
Closing this in favour of #278

**Comment by technophile-04** [comment]
Closing this in favour of #278
