### ISSUE TITLE
un-gitignore hardhat_contracts.ts

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#278]
- We can remove the postinstall script.
- When you deploy your contracts for the your dApp, you need the file to be committed anyway (for Vercel auto-deployements at least)
- Maybe we can also rename it to `deployed_contracts.ts`? Already thinking about foundry....
- It will fix https://github.com/scaffold-eth/se-2/issues/275

The only CONS that I see is that you will always see change on that file when tinkering locally with the smart contracts. But not a big deal.

**Comment by sverps** [comment]
Sounds like a small trade-off compared to the issues it resolves. :+1:

**Comment by damianmarti** [comment]
Yes! And it's useful to have the deployed testnet or mainnet contract address saved on the repository too.

deployed_contracts.ts sounds better!

**Comment by technophile-04** [comment]
> Sounds like a small trade-off compared to the issues it resolves. 👍

> Yes! And it's useful to have the deployed testnet or mainnet contract address saved on the repository too.
    deployed_contracts.ts sounds better!
    
+++
