### ISSUE TITLE
Notifications don't follow the website theme

### ISSUE THREAD

**Issue by kevinjoshi46b** [scaffold-eth/se-2#286]
Why not expand themes to notifications as well?

Something like this:

![a6131032-36ad-41b8-9c8f-6fdce6b8146a](https://user-images.githubusercontent.com/62877695/230453037-10c8181e-2e18-4b97-bd55-13435f46e032.jpg)

![f31864b8-5184-4807-8314-1afcd39c88ae](https://user-images.githubusercontent.com/62877695/230453115-7da4cba7-1db8-4304-a265-0249359bbfc3.jpg)

**Comment by sverps** [comment]
Sounds good. Want to tackle this and create a PR? Or do you prefer we look into it when we have some time?

**Comment by kevinjoshi46b** [comment]
@sverps I would love to upgrade the notifications myself, I will open a PR for it in some time. You can assign the issue to me.

**Comment by kevinjoshi46b** [comment]
I also had one more suggestion.

For making the notifications UI/UX much better why don't we just display some message like "Oops something went wrong! Check console for more details" something on these lines and console log the error.

Since bombarding the huge error message in the notification itself could be overwhelming for normal web3 users.

**Comment by sverps** [comment]
Maybe we can keep that for another issue/pr. There's some pros and cons to that.

**Comment by KcPele** [comment]
> Maybe we can keep that for another issue/pr. There's some pros and cons to that.

what he said here, this is the issue #301 What this issue is handling has to do with the theme

**Comment by kevinjoshi46b** [comment]
Solved by #298
