### ISSUE TITLE
Scrollbar theme remains default light mode even when scaffoldEthDark theme is active

### ISSUE THREAD

**Issue by kevinjoshi46b** [scaffold-eth/se-2#287]
Why not create a custom scrollbar that updates based on website theme?
Currently only browsers default light mode scrollbar appears on both the themes.

**Comment by kevinjoshi46b** [comment]
For reference I have implemented it in my project:
https://github.com/kevinjoshi46b/lsd/blob/396bcd87e37b60b7e19218477e5c2fc3184cf26f/packages/nextjs/styles/globals.css#L34-L48

**Comment by technophile-04** [comment]
Tysm @kevinjoshi46b this is really nice suggestion it looks cool, but I think we are trying to restrain ourselves from presetting any global defaults to keep things minimal and simple 

Also, I remember `::-webkit-scrollbar` has not become a standard yet checkout [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar)...So it might be great if we delegate this to the user 🙌

**Comment by kevinjoshi46b** [comment]
@technophile-04 Ohhh I wasn't aware it isn't a standard. Fair it does make sense to delegate it to users 🙌
