### ISSUE TITLE
Array inputs on the debug page

### ISSUE THREAD

**Issue by austintgriffith** [scaffold-eth/se-2#288]
I don't think you can input arrays on the debug page

for instance:
![image](https://user-images.githubusercontent.com/2653167/230489344-8a070ff2-3279-4992-a6b9-8c666e3298a2.png)

if you make a function that takes an array of addresses 

you should be able to input those addresses like:

[0x894ca23b1CA77857Fd4ee4F224870230e6C357dE, 0x34aA3F359A9D614239015126635CE7732c18fDF3]

**Comment by austintgriffith** [comment]
gaaaaahhhh 

actually this does work

you just have to use quotes

["ADDRESS1","ADDRESS2"]

**Comment by webthethird** [comment]
@austintgriffith I think it would be much better from a UI/UX perspective if we had an `ArrayInput` component, which would start with one `AddressInput`, `BytesInput` etc. (depending on `paramType.type`) next to a little `+` button that would add another of the same input type below the previous one. Then when you hit send, it would combine the values in all of the inputs into an array for you.

**Comment by carletex** [comment]
Hey @webthethird!

I agree! Feel free to create an issue linking this and explaining the issue... and would be great if you want to work on it :)

The only instance where what you are suggesting is worse UX, is when you want to paste a big list. e.g. pasting a list of 20 addresses that you can prepare in your text editor (I've done that before haha). It's fixable tho, we could detect when someone is pasting an array directly, parse it, and convert it to different inputs (this might be iteration 2, tho :D)

Thanks <3

**Comment by webthethird** [comment]
Opened a feature request in the Discussions:
https://github.com/scaffold-eth/scaffold-eth-2/discussions/462
