### ISSUE TITLE
Foundry Integration

### ISSUE THREAD

**Issue by supernovahs** [scaffold-eth/se-2#42]
I would like to contribute to integrate foundry . How should the architecture look like ? A different folder like hardhat would be nice I think , so user will have both options

**Comment by carletex** [comment]
@supernovahs This is something that we will do, but not in the first MVP.

We talked about doing npx templating, so users can select hardhat or foundry when installing.
"npx create-scaffold-eth-app" will prompt the user

I'll ping you.

**Comment by vanshika-srivastava** [comment]
Do we have foundry support?

**Comment by technophile-04** [comment]
> Do we have foundry support?

Hey yes ! You can try foundry using cli:  checkout https://docs.scaffoldeth.io/quick-start/installation#option-2-beta-setup-using-npx-create-ethlatest
