### ISSUE TITLE
Husky + Lint-staged + GH Actions

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#5]
We did something similar on scaffold-eth a few weeks ago. Also check the scaffold-eth-typescript version of it.

https://github.com/scaffold-eth/scaffold-eth/pull/864

Should be pretty similar, but there might be some differences since we are using a different stack.

**Comment by ShravanSunder** [comment]
NOTE:  I would do #6 first

Use scaffold-eth-typescript as a reference:

Nextjs
- For eslint in nextjs see
   - https://github.com/scaffold-eth/scaffold-eth-typescript/blob/release/packages/common/.eslintrc.js 
   - See https://github.com/scaffold-eth/scaffold-eth-typescript/blob/release/packages/nextjs-app-ts/.eslintrc.js and the ignore file in the nextjs folder
   - see `lint` and `format` commands here https://github.com/scaffold-eth/scaffold-eth-typescript/blob/release/packages/nextjs-app-ts/package.json

Hardhat
- For eslint in hardhat: https://github.com/scaffold-eth/scaffold-eth-typescript/blob/release/packages/solidity-ts/.eslintrc.js and ignore file
- See package commands for lint, solhint, format:  - For lint staged see: https://github.com/scaffold-eth/scaffold-eth-typescript/blob/release/package.json#L85

lint staged
- For lint staged see: https://github.com/scaffold-eth/scaffold-eth-typescript/blob/release/package.json#L85

actions:
- see commands here https://github.com/scaffold-eth/scaffold-eth-typescript/blob/release/.github/workflows/pull-request-nextjs.yml for pr WORKFLOWS

**Comment by carletex** [comment]
#6 (yarn 3) is done
