### ISSUE TITLE
Loading page indicator

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#62]
Show a loading / progress indicator / change page opacity when switching between pages. If not, sometimes clicking a link doesn't seem to do anything.

On BGv3 I'm using https://ricostacruz.com/nprogress/, but we can explore other options.

The key is setting up events listeners on nextjs route events:

```
    router.events.on("routeChangeStart", handleStart);
    router.events.on("routeChangeComplete", handleStop);
    router.events.on("routeChangeError", handleStop);
```

**Comment by damianmarti** [comment]
There is a nextjs component based on nprogress that maybe we can use: https://www.npmjs.com/package/nextjs-progressbar

**Comment by damianmarti** [comment]
Blog post with data on how to add nprogress on nextjs: https://blog.openreplay.com/how-to-build-a-progress-bar-indicator-for-next-js

**Comment by damianmarti** [comment]
@carletex do you think that is best to add nprogress or the component that wraps nprogress?
