### ISSUE TITLE
Footer middle info

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#67]
![image](https://user-images.githubusercontent.com/2486142/207105335-cd3bcc0f-9e06-4f0f-b048-d2b8fc22f6df.png)

The full footer will look like this:

![image](https://user-images.githubusercontent.com/2486142/207105475-e1970ae8-ba69-4673-bb57-68a9723f3db2.png)

**Comment by damianmarti** [comment]
Is "BuidlGuidl" a link to the BuidlGuidl website? Where "Support" links to?

**Comment by carletex** [comment]
Hey @damianmarti . Yes, sorry, I should've specified that.

**Fork me:** link to this repo
**BuidlGuidl:** link to the the BG website (let's have the link underlined also)
**Support:** link to the TG channel (for now let's use the same one as [SE-1](https://t.me/joinchat/KByvmRe5wkR-8F_zz6AjpA), but we need to discuss that)

Let's create a `Footer.tsx` component for it.

**Comment by carletex** [comment]
Fixed on #75
