### ISSUE TITLE
Creating custom Toast system with zustand + tailwind

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/se-2#68]
## Current Behavior : 
Currently, the way we are handling toast is a bit messy. Checkout [toast.tsx](https://github.com/scaffold-eth/se-2/blob/master/packages/nextjs/components/scaffold-eth/toast.tsx), it has two Toast wrappers one for normal toasts and other specifically for transactions :( . In some places, we are directly using toast from [react-hot-toast](https://react-hot-toast.com/) eg : [here](https://github.com/scaffold-eth/se-2/blob/8700751c826685aff73e857616cccf72dc9ea9ec/packages/nextjs/hooks/scaffold-eth/useTransactor.tsx#L80) and in some places we are using our toast wrappers from  [taost.tsx](https://github.com/scaffold-eth/se-2/blob/master/packages/nextjs/components/scaffold-eth/toast.tsx) eg : [here](https://github.com/scaffold-eth/se-2/blob/8700751c826685aff73e857616cccf72dc9ea9ec/packages/nextjs/hooks/scaffold-eth/useTransactor.tsx#L41). 

## Expected Behavior : 
Let's create our own custom toast system with zustand + (tailwind, daisyUI) which is generic and can be easily utilized by any component. 

### Some basic things to have : 
- [ ] toastType : error, success
- [ ] message : toast message
- [ ] close button

### Good to have stuff : 
- [ ] toastType : loading
- [ ] toastPostion : 'bottomLeft' | 'topRight' ... etc
- [ ] duration: toast automatically closes after this duration

## Some references : 
1) [Toast component with zustand + tailwind + framermotion](https://dev.to/patrickxin/build-a-toast-component-with-react-from-scratch-mlb)
2) [Toast in react with zustand](https://blog.logrocket.com/implementing-animated-toasts-in-react/)
3) [Toast notification system with redux](https://www.deployhq.com/blog/toast-notification-system-in-a-react-redux-application)
4) [daisyUI toast component](https://daisyui.com/components/toast/)

**Comment by carletex** [comment]
@technophile-04 as we discussed on DMs, let's keep using hot-toast + custom wrapper (vs rolling our own solution).

Some ideas we talked about:
- Unifying Toast & txToast.
- The toast could take JSX as a message (instead of string), that way we can compose the message in the caller (no need to pass some params, like the blockexplorer link)
- Think if we'd need to pass `{ options }` on the call `toast.success("<>My message with <span>JSX</span></>", { options });`
