### ISSUE TITLE
Default Solidity Contract

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#80]
On SE-1 we have a basic [set purpose contract](https://github.com/scaffold-eth/scaffold-eth/blob/master/packages/hardhat/contracts/YourContract.sol) as the default solidity contract.

Let's discuss what would be good to have as the **default contract on SE-2**.

I feel that we could have:

- More types: address (owner?), uint (counter?), array / struct?
- Payable & non payable function
- Withdraw function?
- Extending some openzeppelin?
..

I think having this out of the box, make the /debug page richer. It will also be a key part of #81 

P.S: Right now, on the [SE-2 contract](https://github.com/scaffold-eth/scaffold-eth/blob/master/packages/hardhat/contracts/YourContract.sol) we have a few pointless stuff. (the intent was to the display all the posible types / cases on the debug page to do the UI/UX correctly)

**Comment by damianmarti** [comment]
I think that maybe we can have 2 example contracts. One really simple, like the Purpose contract and another one with more features, to be able to have a more complete example page based on it. What do you think?

**Comment by damianmarti** [comment]
The reason to have two contracts is to keep the first contract simple to new users.

**Comment by technophile-04** [comment]
**Here are some of my contract ideas:**

1) v2 of Purpose contract : 
      - The idea is - In the beginning, you have your(owner) purpose set and once the contract is deployed people can change your purpose but there will be a minimum required amount to change the purpose.
      - Only the owner can withdraw the funds
      - Some data structures : mapping(address => purpose), event(address, purpose, amount sent), Counter(noOfTime purpose changed)
      - don't know if it makes sense 😅

2)  FundMe / By me a Coffee contract : 
      - fund me example [here](https://github.com/technophile-04/hardhat-codes/blob/main/hh-fund-me-ts/contracts/FundMe.sol)
      - By me a Coffee example [here](https://docs.alchemy.com/docs/how-to-build-buy-me-a-coffee-defi-dapp)
      - these are just some ideas and we can add/remove stuff accordingly
3) YourNFT contract from se-typescript : 
      - an example is [here](https://github.com/scaffold-eth/scaffold-eth-typescript/blob/release/packages/solidity-ts/contracts/YourNFT.sol)
  
4) A simpler and more robust version of the challenge-1-staking contract : 
      - It will be simple but we can have some more data structures like structs and all.
      
I agree with Damu that it shouldn't be a complex contract and must be intuitive and even a beginner should be able to grasp it in one go. 

Having 2 contracts is a nice idea but maybe we can have 1 contract which is beginner-friendly and also makes /debug and Example UI richer because at the beginning it was a little bit frustrating to me in se-typescript(which had/has 2 contracts) and you need to remove deployment and UI of another contract(this is subjective to me) other than that 2 contracts is also a good option

**Comment by carletex** [comment]
Thanks you for this @damianmarti & @technophile-04 <3

> I agree with Damu that it shouldn't be a complex contract and must be intuitive and even a beginner should be able to grasp it in one go.

+1

>  Having 2 contracts is a nice idea but maybe we can have 1 contract which is beginner-friendly and also makes /debug and Example UI richer because at the beginning it was a little bit frustrating to me in se-typescript(which had/has 2 contracts) and you need to remove deployment and UI of another contract(this is subjective to me) other than that 2 contracts is also a good option where we have the freedom of keeping 2nd contract more robust and a bit complex showing all the abilities of se-2

+1

So maybe we can try to find the sweet spot with 1 contract?? Keeping it simple, but having some mappings, payable, etc. I like the idea of a Purpose contract v2.

I'll say, let's try and see how it feels.

**Comment by austintgriffith** [comment]
Awesome discussions here and spending time finding the right level of complexity! 

My vote is leaning toward a simple, single contract with just a few of the basics. 

Hopefully this repo will also be forked a lot and the forks will have more complex contracts. 

Def want the two contract thing to be a very simple next step too.

**Comment by carletex** [comment]
Just merged a draft of a Purpose contract v2. Let's play with it and see how it feels.

Thanks all!!
