### ISSUE TITLE
Show the /debug result of a TX in a collapsible way

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#89]
When sending a TX on the /debug page, the result looks like this:

![image](https://user-images.githubusercontent.com/2486142/210998807-670d369d-f151-4685-828f-b7ed17cedecf.png)

Maybe we can show the result in a similar way as we do in abi ninja.

![image](https://user-images.githubusercontent.com/2486142/210999684-dca1bf55-4eec-4401-b481-5880b171caf7.png)

![image](https://user-images.githubusercontent.com/2486142/210999641-6b3cdf9d-ea6e-4190-9a29-7c4f7437858a.png)

**Comment by simplemachine92** [comment]
Couldn't assign myself, but I'm on this.

**Comment by simplemachine92** [comment]
https://github.com/scaffold-eth/se-2/pull/90
